import cv2
import numpy as np
from PIL import Image
from PIL.ExifTags import TAGS
import os
import re

# -------------------------
# AI TOOLS + FINGERPRINTS
# -------------------------
AI_TOOLS = {
    "Google Gemini Image": [
        "gemini", "google ai", "google image", "bard"
    ],
    "Gemini Nano": [
        "nano", "gemini nano"
    ],
    "Nano Banana": [
        "nano banana", "banana ai", "banana image"
    ],
    "Midjourney": [
        "midjourney", "mj", "cinematic", "dramatic lighting"
    ],
    "Stable Diffusion": [
        "stable diffusion", "sd", "diffusion", "dreambooth", "anime"
    ],
    "DALL·E": [
        "dall-e", "openai", "clean render"
    ],
    "Adobe Firefly": [
        "firefly", "adobe"
    ],
    "Leonardo AI": [
        "leonardo", "fantasy art", "sharp illustration"
    ],
    "Bing Image Creator": [
        "bing", "microsoft"
    ],
    "Playground AI": [
        "playground"
    ],
    "NightCafe": [
        "nightcafe"
    ],
    "Unknown AI": []
}

# -------------------------
# WATERMARK / LOGO HINTS
# -------------------------
WATERMARK_HINTS = [
    "generated by",
    "ai generated",
    "made with ai",
    "stable diffusion",
    "midjourney",
    "openai",
    "leonardo.ai",
    "google gemini",
    "gemini ai",
    "nano banana",
    "banana ai"
]

# -------------------------
# METADATA / EXIF CHECK
# -------------------------
def check_exif(image_path):
    try:
        img = Image.open(image_path)
        exif_data = img._getexif()

        if not exif_data:
            return True, "No EXIF metadata"

        for tag, value in exif_data.items():
            name = TAGS.get(tag, tag)
            val = str(value).lower()

            if name == "Software":
                if any(k in val for k in [
                    "ai", "diffusion", "generator", "openai",
                    "gemini", "nano", "banana"
                ]):
                    return True, f"AI software tag: {value}"

        return False, "Camera metadata present"
    except:
        return True, "EXIF unreadable"

# -------------------------
# NOISE / TEXTURE ANALYSIS
# -------------------------
def analyze_noise(image_path):
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        return 0.4, "Unreadable image"

    lap_var = cv2.Laplacian(img, cv2.CV_64F).var()

    if lap_var < 25:
        return 0.7, "Over-smooth synthetic texture"
    if lap_var > 1500:
        return 0.6, "Over-sharp AI edges"

    return 0.3, "Natural noise level"

# -------------------------
# WATERMARK / LOGO SCAN
# -------------------------
def detect_watermark(image_path):
    filename = os.path.basename(image_path).lower()

    for hint in WATERMARK_HINTS:
        if hint in filename:
            return True, f"Watermark hint: {hint}"

    return False, "No watermark detected"

# -------------------------
# AI TOOL PREDICTION
# -------------------------
def predict_tool(image_path):
    name = os.path.basename(image_path).lower()

    for tool, keywords in AI_TOOLS.items():
        for k in keywords:
            if k in name:
                return tool

    return "Unknown AI"

# -------------------------
# MAIN IMAGE DETECTOR
# -------------------------
def detect_image_ai(image_path):
    score = 0.0
    signals = []

    exif_ai, exif_reason = check_exif(image_path)
    if exif_ai:
        score += 0.3
        signals.append(exif_reason)

    noise_score, noise_reason = analyze_noise(image_path)
    score += noise_score
    signals.append(noise_reason)

    wm_ai, wm_reason = detect_watermark(image_path)
    if wm_ai:
        score += 0.4
        signals.append(wm_reason)

    is_ai = score >= 0.6

    tool = predict_tool(image_path) if is_ai else "Real Camera"

    return {
        "is_ai": is_ai,
        "confidence": round(min(score, 1.0) * 100, 2),
        "tool": tool,
        "synthetic_id": f"SYN-{abs(hash(image_path)) % 1000000}",
        "signals": signals
    }

# -------------------------
# VIDEO DETECTOR
# -------------------------
def detect_video_ai(frame_results):
    ai_frames = [r for r in frame_results if r["is_ai"]]
    total = len(frame_results)

    ratio = len(ai_frames) / total if total else 0

    tool_votes = {}
    for r in ai_frames:
        tool_votes[r["tool"]] = tool_votes.get(r["tool"], 0) + 1

    top_tool = max(tool_votes, key=tool_votes.get) if tool_votes else "Unknown"

    return {
        "is_ai": ratio >= 0.5,
        "confidence": round(ratio * 100, 2),
        "tool": top_tool,
        "synthetic_id": f"SYN-VIDEO-{len(ai_frames)}F"
    }
